<?php
    /**
     * Copyright © Magento, Inc. All rights reserved.
     * See COPYING.txt for license details.
     */

    // @codingStandardsIgnoreFile

?>

<?php
    /** @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox $block */

    /** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
    $priceModel = $block->getPriceType('regular_price');

    /** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
    $finalPriceModel = $block->getPriceType('final_price');
    /** @var $product \Magento\Catalog\Model\Product */
    $product = $block->getSaleableItem();
    $idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
    $schema = ($block->getZone() == 'item_view') ? true : false;
    $configuredSimple = $block->getConfiguredSimple();
    $hasSpecialPrice = false;
    if ($configuredSimple) {
        $configuredRegularPrice = $configuredSimple->getPriceInfo()->getPrice("regular_price")->getValue();
        $configuredFinalPrice = $configuredSimple->getPriceInfo()->getPrice("final_price")->getValue();
        if ($configuredFinalPrice < $configuredRegularPrice) {
            $hasSpecialPrice = true;
        }
    }
?>
<?php if (($block->hasSpecialPrice() && !$configuredSimple) || $hasSpecialPrice): ?>
    <span class="old-price sly-old-price">
        <?php /* @escapeNotVerified */
            echo $block->renderAmount($priceModel->getAmount(), [
                'display_label' => "statt",
                'price_id' => $block->getPriceId('old-price-' . $idSuffix),
                'price_type' => 'oldPrice',
                'include_container' => true,
                'skip_adjustments' => true,
                'layered_configured_price' => ($hasSpecialPrice) ? $configuredRegularPrice : false,
            ]); ?>
    </span>
<?php endif; ?>
<?php if (!$block->isProductList() && $block->hasSpecialPrice()): ?>
    <div>
        <div class="old-price sly-old-price"><div id="discount"></div></div>
    </div>
<?php endif; ?>
<div class="price-start">
    <?php if ($block->isProductList()): ?>
        <?php if (!$block->hasSpecialPrice()): ?>
            <div class="block"></div>
        <?php endif; ?>
    <?php endif; ?>
    <span class="normal-price">
        <?php if (($block->isProductList()) && !$configuredSimple): ?>
            <div class="label">ab</div>
        <?php endif; ?>
        <?php
            $arguments = [
                'display_label' => '',
                'price_id' => $block->getPriceId('product-price-' . $idSuffix),
                'price_type' => 'finalPrice',
                'include_container' => true,
                'layered_configured_price' => ($configuredSimple) ? $configuredSimple->getPriceInfo()->getPrice('final_price')->getValue() : false,
                'schema' => $schema
            ];

            /* @noEscape */
            echo $block->renderAmount($finalPriceModel->getAmount(), $arguments);
        ?>
    </span>
</div>
<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()): ?>
        <a href="<?= /* @escapeNotVerified */
            $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
            <?= /* @escapeNotVerified */
                $block->renderAmountMinimal() ?>
        </a>
    <?php else: ?>
        <span class="minimal-price-link">
            <?= /* @escapeNotVerified */
                $block->renderAmountMinimal() ?>
        </span>
    <?php endif ?>
<?php endif; ?>

